version: '3'
services:
  next:
    image: node:16.10.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'npm run dev'
    ports:
      - '3000:3000'
    stdin_open: true