version: '3'
services:
  next:
    image: node:16.10.0-alpine
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm run dev'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true