import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { createStyles, makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';
import { grey } from '@mui/material/colors'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      backgroundColor: grey[200]
    },
  }),
);

const Home: NextPage = () => {
  const classes = useStyles()
  return (
    <div className={classes.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
      <h2>
        <Link href="/about">
          <button>Go about Page.</button>
        </Link>
      </h2>
    </div>
  )
}

export default Home
